version: '3'
name: blog-app-angela
services:
  mysql_blog2:
    build: ./mysql_docker
    ports:
      - "33069:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_password
      MYSQL_DATABASE: blog_db2
    volumes:
      - "mysql-data:/var/lib/mysql" 
  api: 
    build: ./api
    ports:
      - "3010:3000"
    depends_on:
      - mysql_blog2
volumes:
  mysql-data:
    driver: "local"




